//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsMaster
    {
        public int AccountID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string AccountNameinArabic { get; set; }
        public string AccountNameinEnglish { get; set; }
        public string Description { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<double> ClosingBalance { get; set; }
        public Nullable<double> DebitBalance { get; set; }
        public Nullable<double> CreditBalance { get; set; }
        public string ParentAccountID { get; set; }
        public string Status { get; set; }
        public string AccountOwner { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public Nullable<int> OwnerType { get; set; }
        public Nullable<int> AccountType { get; set; }
    }
}
