//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveInstalltion
    {
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public int InstallationID { get; set; }
        public string MachineIP { get; set; }
        public string MachineName { get; set; }
        public string MACID { get; set; }
        public string ProcessorID { get; set; }
        public string ProductKey { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
