//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal
    {
        public int AppraisalID { get; set; }
        public Nullable<int> AppraisalOwnerType { get; set; }
        public Nullable<int> AppraisalSubjectType { get; set; }
        public Nullable<int> AppraisalType { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> IsPeriodic { get; set; }
        public Nullable<int> IsScheduled { get; set; }
        public string AppraisalArabicDescription { get; set; }
        public string AppraisalEnglishDescription { get; set; }
    }
}
