//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public string BankCode { get; set; }
        public string BankArabicName { get; set; }
        public string BanKEnglishName { get; set; }
        public int CountryId { get; set; }
    }
}
