//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Nullable<int> AvailableAmount { get; set; }
        public int BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> BookType { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string LibraryNumber { get; set; }
        public Nullable<int> NumberofUnits { get; set; }
        public Nullable<float> PurchasePrice { get; set; }
        public Nullable<float> SalePrice { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> Volume { get; set; }
    }
}
