//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInfo
    {
        public string BusNo { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string DriverID { get; set; }
        public Nullable<int> NumberofSeats { get; set; }
        public Nullable<System.DateTime> BusLicenseDate { get; set; }
        public Nullable<int> Ownership { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> RentValue { get; set; }
        public string BusOwner { get; set; }
        public Nullable<int> ParkingArea { get; set; }
        public Nullable<int> StandbyDay1 { get; set; }
        public Nullable<int> StandbyDay2 { get; set; }
        public Nullable<int> StandbyDay3 { get; set; }
        public Nullable<int> StandbyDay4 { get; set; }
        public Nullable<int> StandbyDay5 { get; set; }
        public Nullable<int> PicnicAllowed { get; set; }
        public string AttendantID { get; set; }
        public string SecondAttendantID { get; set; }
        public Nullable<int> BusCurrentStatus { get; set; }
        public string PlateNumber { get; set; }
        public int BusID { get; set; }
    }
}
