//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusShiftRotationSchedule
    {
        public string BusNo { get; set; }
        public int BusShiftRotationScheduleItemID { get; set; }
        public string DriverID { get; set; }
        public string FirstAttendantID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolYear { get; set; }
        public string SecondAttendantID { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
    }
}
