//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string ArabicCurrency { get; set; }
        public string ArabicName { get; set; }
        public string ArabicNationality { get; set; }
        public string CountryCode { get; set; }
        public string CurrencyCode { get; set; }
        public string EnglishCurrency { get; set; }
        public string EnglishName { get; set; }
        public string EnglishNationality { get; set; }
        public int ID { get; set; }
        public string MobileNumberLength { get; set; }
        public string MobileNumberValidStart { get; set; }
        public string NationalIdentificationArabic { get; set; }
        public string NationalIdentificationEnglish { get; set; }
        public byte[] Flag { get; set; }
    }
}
