//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int DiscountID { get; set; }
        public string DiscountDescription { get; set; }
        public string DiscountQuestion { get; set; }
        public Nullable<int> DiscountTypeID { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
