//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string DocumentArabicDescription { get; set; }
        public string DocumentEnglishDescription { get; set; }
        public int DocumentID { get; set; }
        public string DocumentOwnerID { get; set; }
        public Nullable<int> DocumentOwnerType { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public string FileExtension { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
