//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalStudentGuardDetail
    {
        public int StudentID { get; set; }
        public Nullable<int> GuardianID { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> FatherQualification { get; set; }
        public Nullable<int> MotherQualification { get; set; }
        public Nullable<int> FatherSpecialization { get; set; }
        public Nullable<int> MotherSpecialization { get; set; }
        public string FatherJob { get; set; }
        public string MotherJob { get; set; }
        public string FatherWorkPhone { get; set; }
        public string MotherWorkPhone { get; set; }
        public string MotherMobile { get; set; }
        public string FatherMobile { get; set; }
        public string FatherEmail { get; set; }
        public string MotherEmail { get; set; }
        public string MailBox { get; set; }
        public string PostalCode { get; set; }
        public string SmsNumber { get; set; }
    }
}
