//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportanceType
    {
        public string ImportanceArabicText { get; set; }
        public string ImportanceEnglishText { get; set; }
        public int ImportanceTypeID { get; set; }
    }
}
