//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualTimetable
    {
        public Nullable<int> SchoolClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolYear { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string TeacherID { get; set; }
        public int TimetableEntityID { get; set; }
        public Nullable<int> TimetableItemID { get; set; }
    }
}
