//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTeams_Sessions
    {
        public int MSTeamSessionID { get; set; }
        public string StaffID { get; set; }
        public int MSTeamsAccountID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string MeetingTitle { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string JoinURL { get; set; }
        public string JoinWebURL { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
