//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Nullable<System.DateTime> DateRead { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public string DesitinationID { get; set; }
        public Nullable<int> DestinationType { get; set; }
        public Nullable<int> ImportanceLevel { get; set; }
        public int NotificationID { get; set; }
        public string NotificationText { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolYear { get; set; }
        public string SourceID { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateDelegated { get; set; }
        public Nullable<System.DateTime> DateSeen { get; set; }
        public Nullable<System.DateTime> DateReplied { get; set; }
    }
}
