//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolBranch
    {
        public int SchoolID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string SchoolArabicName { get; set; }
        public string SchoolEnglishName { get; set; }
        public string SchoolContactNumber { get; set; }
        public Nullable<int> Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> SchoolCurrency { get; set; }
        public Nullable<int> YardArea { get; set; }
        public Nullable<int> MaxSchoolStudents { get; set; }
        public Nullable<int> ClassroomArea { get; set; }
        public Nullable<int> MaxStudentsinClassroom { get; set; }
        public Nullable<int> CurrentNumberofStudents { get; set; }
        public bool IsNew { get; set; }
        public bool IsRegistered { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
    }
}
