//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionDistribution
    {
        public int SessionDistributionID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public Nullable<int> Day1Sessions { get; set; }
        public Nullable<int> Day2Sessions { get; set; }
        public Nullable<int> Day3Sessions { get; set; }
        public Nullable<int> Day4Sessions { get; set; }
        public Nullable<int> Day5Sessions { get; set; }
    }
}
