//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffJobDetail
    {
        public string StaffID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<int> Specialization { get; set; }
        public Nullable<int> YearOfExperience { get; set; }
        public Nullable<int> YearofGraduation { get; set; }
        public string Institution { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UseSchoolTransportation { get; set; }
        public Nullable<int> BusAttendance { get; set; }
        public Nullable<int> ComingTourID { get; set; }
        public Nullable<int> GoingTourID { get; set; }
        public Nullable<int> ComingTourOrder { get; set; }
        public Nullable<int> LeaveswithSchoolBus { get; set; }
        public Nullable<int> GoingTourOrder { get; set; }
        public string SchoolStaffNumber { get; set; }
        public string AssistedTeacherID { get; set; }
    }
}
