//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSettingsperSchool
    {
        public int SchoolID { get; set; }
        public Nullable<int> LastInvoiceNumber { get; set; }
        public Nullable<int> OptionalArabicFields { get; set; }
        public Nullable<int> OptionalEnglishFields { get; set; }
        public Nullable<int> OptionalFamilyDetails { get; set; }
        public Nullable<int> OptionalThirdName { get; set; }
        public Nullable<int> BusScheduleDateType { get; set; }
        public Nullable<int> BusScheduleType { get; set; }
        public Nullable<int> NumberofBusTrips { get; set; }
        public Nullable<int> TimetableType { get; set; }
        public Nullable<int> SubjectDistributionMethod { get; set; }
        public Nullable<int> SubjectforClassorSection { get; set; }
        public Nullable<int> CurrencyOptions { get; set; }
        public Nullable<int> BusAttendantAssigningMethod { get; set; }
    }
}
