//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public string CurrentAcademicYear { get; set; }
        public string DocumentsPath { get; set; }
        public Nullable<int> LastDocumentID { get; set; }
        public Nullable<int> LastStaffID { get; set; }
        public Nullable<int> LastStudentID { get; set; }
    }
}
