//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherExperience
    {
        public Nullable<int> AppraisalValue { get; set; }
        public Nullable<int> Curriculum { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolYear { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public int TeacherExperienceID { get; set; }
        public string TeacherID { get; set; }
        public string YearsofExperience { get; set; }
        public Nullable<double> TeacherWeight { get; set; }
    }
}
