//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualMeeting
    {
        public int VirtualSessionID { get; set; }
        public string MeetingTitle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string StaffID { get; set; }
        public Nullable<bool> StatusID { get; set; }
        public bool IsDeleted { get; set; }
        public int MeetingID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
