//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicCalendar1
    {
        public int OccasionID { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
        public Nullable<int> OccasionType { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<int> NumberofDays { get; set; }
        public Nullable<int> Vacation { get; set; }
        public Nullable<int> CalendarID { get; set; }
        public string SchoolYear1 { get; set; }
    }
}
