//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsDetail
    {
        public int TransactionID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string TransactionArabicDescription { get; set; }
        public string TransactionEnglishDescription { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> AmountType { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string DocumentNo { get; set; }
        public string TransactionOwner { get; set; }
        public string Note { get; set; }
    }
}
