//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookUnit
    {
        public Nullable<int> BookID { get; set; }
        public int BookUnitID { get; set; }
        public Nullable<int> UnitNumber { get; set; }
        public string UnitTitle { get; set; }
        public Nullable<int> NumberofChapters { get; set; }
    }
}
