//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusMaintenance
    {
        public int MaintenanceID { get; set; }
        public string BusNo { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<int> MaintenanceType { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Workshop { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
