//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusTour
    {
        public int TourID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string BusNo { get; set; }
        public string TourArabicName { get; set; }
        public string TourEnglishName { get; set; }
        public Nullable<int> TourArea { get; set; }
        public Nullable<int> MaxNoofStudents { get; set; }
        public Nullable<int> NumberofStudents { get; set; }
        public string TourAttendant { get; set; }
        public Nullable<int> EstimatedTourTime { get; set; }
        public Nullable<int> EstimatedFuelConsumption { get; set; }
        public Nullable<int> TourDirection { get; set; }
        public Nullable<System.DateTime> StratingTime { get; set; }
        public Nullable<double> StraightDistanceFromSchool { get; set; }
        public Nullable<double> BestDistanceFromSchool { get; set; }
        public string SecondAttendant { get; set; }
    }
}
