//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusTrackNavigation
    {
        public long MoveSequnce { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string BusNumber { get; set; }
        public string MoveDate { get; set; }
        public string MoveTime { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string BusSpeed { get; set; }
        public string RoadSpeed { get; set; }
        public Nullable<double> FuelLevel { get; set; }
        public string StudentInBus { get; set; }
        public Nullable<int> TripNumPerDay { get; set; }
    }
}
