//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public int ClassRoomID { get; set; }
        public int CLassRoomNumber { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> Building { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> NumberofChairs { get; set; }
        public Nullable<int> Available { get; set; }
        public string RoomArabicName { get; set; }
        public string RoomEnglishName { get; set; }
        public string BuildingArabicName { get; set; }
        public string BuildingEnglishName { get; set; }
    }
}
