//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardType
    {
        public int CreditCardTypeID { get; set; }
        public string CreditCardTypeinArabic { get; set; }
        public string CreditCardTypeinEnglish { get; set; }
    }
}
