//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DocumentTypeArabicDescription { get; set; }
        public string DocumentTypeEnglishDescription { get; set; }
        public int DocumentTypeID { get; set; }
    }
}
