//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumrntCustomizedProperty
    {
        public string CustomPropertyArabicDescription { get; set; }
        public Nullable<System.DateTime> CustomPropertyCreationDate { get; set; }
        public string CustomPropertyDefaultValue { get; set; }
        public string CustomPropertyEnglishDescription { get; set; }
        public Nullable<int> CustomPropertyFieldSize { get; set; }
        public string CustomPropertyFormat { get; set; }
        public int CustomPropertyID { get; set; }
        public Nullable<int> CustomPropertyRequired { get; set; }
        public Nullable<int> CustomPropertyType { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public Nullable<int> LocalLookupID { get; set; }
    }
}
