//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Remoting.Messaging;

    public partial class ExternalStudent
    {
        public int StudentID { get; set; }
        public string StudentArabicName { get; set; }
        public string StudentEnglishName { get; set; }
        public string NationalNumber { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> GuardianID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<int> MotherID { get; set; }
        public string ResidencyNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> GuardianRelationship { get; set; }
        public byte[] Photo { get; set; }
        public string Photo_A { get; set; }
        public Nullable<int> TransportDirectionID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string BirthPlace { get; set; }
        public byte[] BirthCertificatePhoto { get; set; }
        public byte[] FamilyBookPhoto { get; set; }
        public byte[] LastYearCertificate { get; set; }
    }
}
