//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalStudentAdress
    {
        public int AddressID { get; set; }
        public int GuardianID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Building { get; set; }
        public Nullable<int> Flat { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public int TransportDirectionID { get; set; }
    }
}
