//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeeID { get; set; }
        public string FeeArabicName { get; set; }
        public string FeeEnglishName { get; set; }
        public Nullable<int> FeeType { get; set; }
        public Nullable<double> FeeAmount { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int CurriculumID { get; set; }
    }
}
