//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardian
    {
        public int GuardianID { get; set; }
        public string GuardianArabicName { get; set; }
        public string GuardianEnglishName { get; set; }
        public string NationalNumber { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Religion { get; set; }
        public string ResidencyNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> CreditCardType { get; set; }
        public string CreditCardNumber { get; set; }
        public string NameonCreditCard { get; set; }
        public string CreditCardExpiryDate { get; set; }
        public string CreditCardCode { get; set; }
        public string MobileNumber { get; set; }
    }
}
