//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardianSchool
    {
        public int ID { get; set; }
        public Nullable<int> GuardianID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
