//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Headquarters
    {
        public int CompanyID { get; set; }
        public string CompanyArabicName { get; set; }
        public string CompanyEnglishName { get; set; }
        public Nullable<int> Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string ProductKey { get; set; }
    }
}
