//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupValue
    {
        public Nullable<int> CustomPropertyID { get; set; }
        public string LookupValue1 { get; set; }
        public int LookupValueID { get; set; }
        public Nullable<int> LookupValueLanguageID { get; set; }
    }
}
