//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappedField
    {
        public int FieldID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SystemFieldID { get; set; }
        public string TemplateField { get; set; }
        public Nullable<int> FeeFieldID { get; set; }
        public Nullable<int> FeeorSystem { get; set; }
    }
}
