//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherStudentDetail
    {
        public int ID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> Behavior { get; set; }
        public string BehaviorNotes { get; set; }
        public Nullable<int> BloodType { get; set; }
        public string DiseaseType { get; set; }
        public Nullable<int> FamilyOrder { get; set; }
        public Nullable<double> FamilyTotalMonthlyIncome { get; set; }
        public Nullable<int> HasChronicDisease { get; set; }
        public string HealthNotes { get; set; }
        public Nullable<int> LivesWith { get; set; }
        public Nullable<int> NumberofBrothers { get; set; }
        public Nullable<int> NumberofSisters { get; set; }
        public Nullable<int> PhysicalStatus { get; set; }
        public Nullable<int> SpecialCare { get; set; }
        public Nullable<int> SpecialResidenceConditions { get; set; }
        public string Talents { get; set; }
        public Nullable<int> ValedictorianinSubject { get; set; }
        public Nullable<int> WeakinSubject { get; set; }
    }
}
