//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBank
    {
        public Nullable<int> BookUnitID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<float> QuestionExamWeight { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> QuestionLevel { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> SubjectID { get; set; }
    }
}
