//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolClass
    {
        public int SchoolClassID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public string SchoolClassEnglishName { get; set; }
        public string SchoolClassArabicName { get; set; }
        public bool Coeducation { get; set; }
        public bool Male { get; set; }
        public bool Female { get; set; }
    }
}
