//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolSetting
    {
        public int SchoolID { get; set; }
        public Nullable<int> NumberofClassRooms { get; set; }
        public Nullable<int> NumberofChairsPerClass { get; set; }
        public Nullable<int> NumberofSessionsPerDay { get; set; }
        public Nullable<int> NumberofSessionsPerTeacher { get; set; }
        public Nullable<int> AllowedNumberofStudentsPerYardArea { get; set; }
        public Nullable<int> AllowedNumberofStudentsPerClassroomArea { get; set; }
        public Nullable<int> WeekStartingDay { get; set; }
        public Nullable<System.DateTime> StartingTime { get; set; }
        public Nullable<System.DateTime> FirstClassStartingTime { get; set; }
        public Nullable<int> SessionDuration { get; set; }
        public Nullable<int> BreakBetweenSessionsDuration { get; set; }
        public Nullable<int> BreakDuration { get; set; }
        public Nullable<int> NumberofSemesters { get; set; }
        public Nullable<int> MultiDependantsDiscount { get; set; }
        public Nullable<int> BreakAfterSession { get; set; }
    }
}
