//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public Nullable<int> ClassroomID { get; set; }
        public string SectionCode { get; set; }
        public Nullable<int> MaxNumberofStudents { get; set; }
        public Nullable<int> NumberofStudents { get; set; }
        public Nullable<int> IsFull { get; set; }
        public string SectionArabicName { get; set; }
        public string SectionEnglishName { get; set; }
    }
}
