//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolYear { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> WeekDay { get; set; }
        public Nullable<int> SessionDayOrder { get; set; }
        public Nullable<System.DateTime> SessionTime { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
