//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSalaryDetail
    {
        public string StaffID { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<double> HousingAllowence { get; set; }
        public Nullable<double> TransportationAllowence { get; set; }
        public Nullable<double> OtherAllowence { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public Nullable<float> SocialInsuranceValue { get; set; }
        public string IncomeTaxNumber { get; set; }
        public Nullable<float> IncomeTaxValue { get; set; }
    }
}
