//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFee
    {
        public int StudentFeeID { get; set; }
        public Nullable<int> FeeID { get; set; }
        public string StudentID { get; set; }
        public string AccountNumber { get; set; }
        public string SchoolYear { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> NumberofInstallments { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> IsClosed { get; set; }
    }
}
