//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentStatu
    {
        public int StatusID { get; set; }
        public string StatusArabicText { get; set; }
        public string StatusEnglishText { get; set; }
    }
}
