//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SubjectID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public string SubjectArabicName { get; set; }
        public string SubjectEnglishName { get; set; }
        public Nullable<int> MaxMark { get; set; }
        public Nullable<int> FailMark { get; set; }
        public Nullable<int> NumberOfSessionsPerWeek { get; set; }
        public Nullable<int> SchedulingCondition { get; set; }
        public Nullable<int> SectionID { get; set; }
    }
}
