//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateSetting
    {
        public int TemplateSettingsID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ContractType { get; set; }
        public string ContractTemplateName { get; set; }
        public string ReceiptTemplateName { get; set; }
        public string TemplateArchivePath { get; set; }
        public string SignatoryID { get; set; }
    }
}
