//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportCategory
    {
        public int TransportCategoryID { get; set; }
        public Nullable<int> TransportTypeID { get; set; }
        public Nullable<int> TransportCategoryTypeID { get; set; }
        public Nullable<double> DistanceInMeters { get; set; }
        public Nullable<double> TransportCategoryCostGo { get; set; }
        public Nullable<double> TransportCategoryCostReturn { get; set; }
        public Nullable<double> TransportCategoryCostTwoWay { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
