//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wife
    {
        public int WifeID { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public string WifeArabicName { get; set; }
        public string WifeEnglishName { get; set; }
        public string WifeNationalNumber { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string ResidencyNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> Occupation { get; set; }
    }
}
