//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAbsenceReasonsManager
	{

    void Add(AbsenceReason AbsenceReason);

    void Update(AbsenceReason AbsenceReason);

    void Delete(AbsenceReason AbsenceReason);

    AbsenceReason GetById(short id);
      
    IList<AbsenceReason> GetAll();

    IEnumerable<AbsenceReason> Find(Expression<Func<AbsenceReason, bool>> where, params Expression<Func<AbsenceReason, object>>[] includes);
		
    }

}
