//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAcademicCalendar1sManager
	{

    void Add(AcademicCalendar1 AcademicCalendar1);

    void Update(AcademicCalendar1 AcademicCalendar1);

    void Delete(AcademicCalendar1 AcademicCalendar1);

    AcademicCalendar1 GetById(short id);
      
    IList<AcademicCalendar1> GetAll();

    IEnumerable<AcademicCalendar1> Find(Expression<Func<AcademicCalendar1, bool>> where, params Expression<Func<AcademicCalendar1, object>>[] includes);
		
    }

}
