//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAccountsMastersManager
	{

    void Add(AccountsMaster AccountsMaster);

    void Update(AccountsMaster AccountsMaster);

    void Delete(AccountsMaster AccountsMaster);

    AccountsMaster GetById(short id);
      
    IList<AccountsMaster> GetAll();

    IEnumerable<AccountsMaster> Find(Expression<Func<AccountsMaster, bool>> where, params Expression<Func<AccountsMaster, object>>[] includes);
		
    }

}
