//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAccountOwnerTypesManager
	{

    void Add(AccountOwnerType AccountOwnerType);

    void Update(AccountOwnerType AccountOwnerType);

    void Delete(AccountOwnerType AccountOwnerType);

    AccountOwnerType GetById(short id);
      
    IList<AccountOwnerType> GetAll();

    IEnumerable<AccountOwnerType> Find(Expression<Func<AccountOwnerType, bool>> where, params Expression<Func<AccountOwnerType, object>>[] includes);
		
    }

}
