//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAccountTypesManager
	{

    void Add(AccountType AccountType);

    void Update(AccountType AccountType);

    void Delete(AccountType AccountType);

    AccountType GetById(short id);
      
    IList<AccountType> GetAll();

    IEnumerable<AccountType> Find(Expression<Func<AccountType, bool>> where, params Expression<Func<AccountType, object>>[] includes);
		
    }

}
