//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IActiveInstalltionsManager
	{

    void Add(ActiveInstalltion ActiveInstalltion);

    void Update(ActiveInstalltion ActiveInstalltion);

    void Delete(ActiveInstalltion ActiveInstalltion);

    ActiveInstalltion GetById(short id);
      
    IList<ActiveInstalltion> GetAll();

    IEnumerable<ActiveInstalltion> Find(Expression<Func<ActiveInstalltion, bool>> where, params Expression<Func<ActiveInstalltion, object>>[] includes);
		
    }

}
