//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAgeClassificationsManager
	{

    void Add(AgeClassification AgeClassification);

    void Update(AgeClassification AgeClassification);

    void Delete(AgeClassification AgeClassification);

    AgeClassification GetById(short id);
      
    IList<AgeClassification> GetAll();

    IEnumerable<AgeClassification> Find(Expression<Func<AgeClassification, bool>> where, params Expression<Func<AgeClassification, object>>[] includes);
		
    }

}
