//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAppraisalsManager
	{

    void Add(Appraisal Appraisal);

    void Update(Appraisal Appraisal);

    void Delete(Appraisal Appraisal);

    Appraisal GetById(short id);
      
    IList<Appraisal> GetAll();

    IEnumerable<Appraisal> Find(Expression<Func<Appraisal, bool>> where, params Expression<Func<Appraisal, object>>[] includes);
		
    }

}
