//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAppraisalTypesManager
	{

    void Add(AppraisalType AppraisalType);

    void Update(AppraisalType AppraisalType);

    void Delete(AppraisalType AppraisalType);

    AppraisalType GetById(short id);
      
    IList<AppraisalType> GetAll();

    IEnumerable<AppraisalType> Find(Expression<Func<AppraisalType, bool>> where, params Expression<Func<AppraisalType, object>>[] includes);
		
    }

}
