//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAppraisalValuesManager
	{

    void Add(AppraisalValue AppraisalValue);

    void Update(AppraisalValue AppraisalValue);

    void Delete(AppraisalValue AppraisalValue);

    AppraisalValue GetById(short id);
      
    IList<AppraisalValue> GetAll();

    IEnumerable<AppraisalValue> Find(Expression<Func<AppraisalValue, bool>> where, params Expression<Func<AppraisalValue, object>>[] includes);
		
    }

}
