//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAppraisalMetricsGroupsManager
	{

    void Add(AppraisalMetricsGroup AppraisalMetricsGroup);

    void Update(AppraisalMetricsGroup AppraisalMetricsGroup);

    void Delete(AppraisalMetricsGroup AppraisalMetricsGroup);

    AppraisalMetricsGroup GetById(short id);
      
    IList<AppraisalMetricsGroup> GetAll();

    IEnumerable<AppraisalMetricsGroup> Find(Expression<Func<AppraisalMetricsGroup, bool>> where, params Expression<Func<AppraisalMetricsGroup, object>>[] includes);
		
    }

}
