//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAreasManager
	{

    void Add(Area Area);

    void Update(Area Area);

    void Delete(Area Area);

    Area GetById(short id);
      
    IList<Area> GetAll();

    IEnumerable<Area> Find(Expression<Func<Area, bool>> where, params Expression<Func<Area, object>>[] includes);
		
    }

}
