//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IAttendancesManager
	{

    void Add(Attendance Attendance);

    void Update(Attendance Attendance);

    void Delete(Attendance Attendance);

    Attendance GetById(short id);
      
    IList<Attendance> GetAll();

    IEnumerable<Attendance> Find(Expression<Func<Attendance, bool>> where, params Expression<Func<Attendance, object>>[] includes);
		
    }

}
