//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBankBranchsManager
	{

    void Add(BankBranch BankBranch);

    void Update(BankBranch BankBranch);

    void Delete(BankBranch BankBranch);

    BankBranch GetById(short id);
      
    IList<BankBranch> GetAll();

    IEnumerable<BankBranch> Find(Expression<Func<BankBranch, bool>> where, params Expression<Func<BankBranch, object>>[] includes);
		
    }

}
