//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBloodTypesManager
	{

    void Add(BloodType BloodType);

    void Update(BloodType BloodType);

    void Delete(BloodType BloodType);

    BloodType GetById(short id);
      
    IList<BloodType> GetAll();

    IEnumerable<BloodType> Find(Expression<Func<BloodType, bool>> where, params Expression<Func<BloodType, object>>[] includes);
		
    }

}
