//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBookChaptersManager
	{

    void Add(BookChapter BookChapter);

    void Update(BookChapter BookChapter);

    void Delete(BookChapter BookChapter);

    BookChapter GetById(short id);
      
    IList<BookChapter> GetAll();

    IEnumerable<BookChapter> Find(Expression<Func<BookChapter, bool>> where, params Expression<Func<BookChapter, object>>[] includes);
		
    }

}
