//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBooksManager
	{

    void Add(Book Book);

    void Update(Book Book);

    void Delete(Book Book);

    Book GetById(short id);
      
    IList<Book> GetAll();

    IEnumerable<Book> Find(Expression<Func<Book, bool>> where, params Expression<Func<Book, object>>[] includes);
		
    }

}
