//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusShiftRotationSchedulesManager
	{

    void Add(BusShiftRotationSchedule BusShiftRotationSchedule);

    void Update(BusShiftRotationSchedule BusShiftRotationSchedule);

    void Delete(BusShiftRotationSchedule BusShiftRotationSchedule);

    BusShiftRotationSchedule GetById(short id);
      
    IList<BusShiftRotationSchedule> GetAll();

    IEnumerable<BusShiftRotationSchedule> Find(Expression<Func<BusShiftRotationSchedule, bool>> where, params Expression<Func<BusShiftRotationSchedule, object>>[] includes);
		
    }

}
