//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusMaintenancesManager
	{

    void Add(BusMaintenance BusMaintenance);

    void Update(BusMaintenance BusMaintenance);

    void Delete(BusMaintenance BusMaintenance);

    BusMaintenance GetById(short id);
      
    IList<BusMaintenance> GetAll();

    IEnumerable<BusMaintenance> Find(Expression<Func<BusMaintenance, bool>> where, params Expression<Func<BusMaintenance, object>>[] includes);
		
    }

}
