//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusFuelsManager
	{

    void Add(BusFuel BusFuel);

    void Update(BusFuel BusFuel);

    void Delete(BusFuel BusFuel);

    BusFuel GetById(short id);
      
    IList<BusFuel> GetAll();

    IEnumerable<BusFuel> Find(Expression<Func<BusFuel, bool>> where, params Expression<Func<BusFuel, object>>[] includes);
		
    }

}
