//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusAttendanceSchedulesManager
	{

    void Add(BusAttendanceSchedule BusAttendanceSchedule);

    void Update(BusAttendanceSchedule BusAttendanceSchedule);

    void Delete(BusAttendanceSchedule BusAttendanceSchedule);

    BusAttendanceSchedule GetById(short id);
      
    IList<BusAttendanceSchedule> GetAll();

    IEnumerable<BusAttendanceSchedule> Find(Expression<Func<BusAttendanceSchedule, bool>> where, params Expression<Func<BusAttendanceSchedule, object>>[] includes);
		
    }

}
