//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusTrackNavigationsManager
	{

    void Add(BusTrackNavigation BusTrackNavigation);

    void Update(BusTrackNavigation BusTrackNavigation);

    void Delete(BusTrackNavigation BusTrackNavigation);

    BusTrackNavigation GetById(short id);
      
    IList<BusTrackNavigation> GetAll();

    IEnumerable<BusTrackNavigation> Find(Expression<Func<BusTrackNavigation, bool>> where, params Expression<Func<BusTrackNavigation, object>>[] includes);
		
    }

}
