//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusInfosManager
	{

    void Add(BusInfo BusInfo);

    void Update(BusInfo BusInfo);

    void Delete(BusInfo BusInfo);

    BusInfo GetById(short id);
      
    IList<BusInfo> GetAll();

    IEnumerable<BusInfo> Find(Expression<Func<BusInfo, bool>> where, params Expression<Func<BusInfo, object>>[] includes);
		
    }

}
