//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IBusShiftRotationScheduleforAutomaticBusSchedulesManager
	{

    void Add(BusShiftRotationScheduleforAutomaticBusSchedule BusShiftRotationScheduleforAutomaticBusSchedule);

    void Update(BusShiftRotationScheduleforAutomaticBusSchedule BusShiftRotationScheduleforAutomaticBusSchedule);

    void Delete(BusShiftRotationScheduleforAutomaticBusSchedule BusShiftRotationScheduleforAutomaticBusSchedule);

    BusShiftRotationScheduleforAutomaticBusSchedule GetById(short id);
      
    IList<BusShiftRotationScheduleforAutomaticBusSchedule> GetAll();

    IEnumerable<BusShiftRotationScheduleforAutomaticBusSchedule> Find(Expression<Func<BusShiftRotationScheduleforAutomaticBusSchedule, bool>> where, params Expression<Func<BusShiftRotationScheduleforAutomaticBusSchedule, object>>[] includes);
		
    }

}
