//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IClassroomsManager
	{

    void Add(Classroom Classroom);

    void Update(Classroom Classroom);

    void Delete(Classroom Classroom);

    Classroom GetById(short id);
      
    IList<Classroom> GetAll();

    IEnumerable<Classroom> Find(Expression<Func<Classroom, bool>> where, params Expression<Func<Classroom, object>>[] includes);
		
    }

}
