//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IClasssManager
	{

    void Add(Class Class);

    void Update(Class Class);

    void Delete(Class Class);

    Class GetById(short id);
      
    IList<Class> GetAll();

    IEnumerable<Class> Find(Expression<Func<Class, bool>> where, params Expression<Func<Class, object>>[] includes);
		
    }

}
