//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ICountrysManager
	{

    void Add(Country Country);

    void Update(Country Country);

    void Delete(Country Country);

    Country GetById(short id);
      
    IList<Country> GetAll();

    IEnumerable<Country> Find(Expression<Func<Country, bool>> where, params Expression<Func<Country, object>>[] includes);
		
    }

}
