//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ICurriculumsManager
	{

    void Add(Curriculum Curriculum);

    void Update(Curriculum Curriculum);

    void Delete(Curriculum Curriculum);

    Curriculum GetById(short id);
      
    IList<Curriculum> GetAll();

    IEnumerable<Curriculum> Find(Expression<Func<Curriculum, bool>> where, params Expression<Func<Curriculum, object>>[] includes);
		
    }

}
