//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDepartmentsManager
	{

    void Add(Department Department);

    void Update(Department Department);

    void Delete(Department Department);

    Department GetById(short id);
      
    IList<Department> GetAll();

    IEnumerable<Department> Find(Expression<Func<Department, bool>> where, params Expression<Func<Department, object>>[] includes);
		
    }

}
