//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDesignationTypesManager
	{

    void Add(DesignationType DesignationType);

    void Update(DesignationType DesignationType);

    void Delete(DesignationType DesignationType);

    DesignationType GetById(short id);
      
    IList<DesignationType> GetAll();

    IEnumerable<DesignationType> Find(Expression<Func<DesignationType, bool>> where, params Expression<Func<DesignationType, object>>[] includes);
		
    }

}
