//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDeviceRegistrarsManager
	{

    void Add(DeviceRegistrar DeviceRegistrar);

    void Update(DeviceRegistrar DeviceRegistrar);

    void Delete(DeviceRegistrar DeviceRegistrar);

    DeviceRegistrar GetById(short id);
      
    IList<DeviceRegistrar> GetAll();

    IEnumerable<DeviceRegistrar> Find(Expression<Func<DeviceRegistrar, bool>> where, params Expression<Func<DeviceRegistrar, object>>[] includes);
		
    }

}
