//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDiscountTypesManager
	{

    void Add(DiscountType DiscountType);

    void Update(DiscountType DiscountType);

    void Delete(DiscountType DiscountType);

    DiscountType GetById(short id);
      
    IList<DiscountType> GetAll();

    IEnumerable<DiscountType> Find(Expression<Func<DiscountType, bool>> where, params Expression<Func<DiscountType, object>>[] includes);
		
    }

}






