//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDiscountStudentsManager
	{

    void Add(DiscountStudent DiscountStudent);

    void Update(DiscountStudent DiscountStudent);

    void Delete(DiscountStudent DiscountStudent);

    DiscountStudent GetById(short id);
      
    IList<DiscountStudent> GetAll();

    IEnumerable<DiscountStudent> Find(Expression<Func<DiscountStudent, bool>> where, params Expression<Func<DiscountStudent, object>>[] includes);
		
    }

}
