//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDiscountsManager
	{

    void Add(Discount Discount);

    void Update(Discount Discount);

    void Delete(Discount Discount);

    Discount GetById(short id);
      
    IList<Discount> GetAll();

    IEnumerable<Discount> Find(Expression<Func<Discount, bool>> where, params Expression<Func<Discount, object>>[] includes);
		
    }

}
