//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDisciplineActionsManager
	{

    void Add(DisciplineAction DisciplineAction);

    void Update(DisciplineAction DisciplineAction);

    void Delete(DisciplineAction DisciplineAction);

    DisciplineAction GetById(short id);
      
    IList<DisciplineAction> GetAll();

    IEnumerable<DisciplineAction> Find(Expression<Func<DisciplineAction, bool>> where, params Expression<Func<DisciplineAction, object>>[] includes);
		
    }

}
