//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDocumentTypesManager
	{

    void Add(DocumentType DocumentType);

    void Update(DocumentType DocumentType);

    void Delete(DocumentType DocumentType);

    DocumentType GetById(short id);
      
    IList<DocumentType> GetAll();

    IEnumerable<DocumentType> Find(Expression<Func<DocumentType, bool>> where, params Expression<Func<DocumentType, object>>[] includes);
		
    }

}
