//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDocumentsManager
	{

    void Add(Document Document);

    void Update(Document Document);

    void Delete(Document Document);

    Document GetById(short id);
      
    IList<Document> GetAll();

    IEnumerable<Document> Find(Expression<Func<Document, bool>> where, params Expression<Func<Document, object>>[] includes);
		
    }

}
