//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IDocumrntCustomizedPropertysManager
	{

    void Add(DocumrntCustomizedProperty DocumrntCustomizedProperty);

    void Update(DocumrntCustomizedProperty DocumrntCustomizedProperty);

    void Delete(DocumrntCustomizedProperty DocumrntCustomizedProperty);

    DocumrntCustomizedProperty GetById(short id);
      
    IList<DocumrntCustomizedProperty> GetAll();

    IEnumerable<DocumrntCustomizedProperty> Find(Expression<Func<DocumrntCustomizedProperty, bool>> where, params Expression<Func<DocumrntCustomizedProperty, object>>[] includes);
		
    }

}
