//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IEducationalYearsManager
	{

    void Add(EducationalYear EducationalYear);

    void Update(EducationalYear EducationalYear);

    void Delete(EducationalYear EducationalYear);

    EducationalYear GetById(short id);
      
    IList<EducationalYear> GetAll();

    IEnumerable<EducationalYear> Find(Expression<Func<EducationalYear, bool>> where, params Expression<Func<EducationalYear, object>>[] includes);
		
    }

}






