//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IExternalStudentGuardDetailsManager
	{

    void Add(ExternalStudentGuardDetail ExternalStudentGuardDetail);

    void Update(ExternalStudentGuardDetail ExternalStudentGuardDetail);

    void Delete(ExternalStudentGuardDetail ExternalStudentGuardDetail);

    ExternalStudentGuardDetail GetById(short id);
      
    IList<ExternalStudentGuardDetail> GetAll();

    IEnumerable<ExternalStudentGuardDetail> Find(Expression<Func<ExternalStudentGuardDetail, bool>> where, params Expression<Func<ExternalStudentGuardDetail, object>>[] includes);
		
    }

}
