//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IExternalOtherStudentDetailsManager
	{

    void Add(ExternalOtherStudentDetail ExternalOtherStudentDetail);

    void Update(ExternalOtherStudentDetail ExternalOtherStudentDetail);

    void Delete(ExternalOtherStudentDetail ExternalOtherStudentDetail);

    ExternalOtherStudentDetail GetById(short id);
      
    IList<ExternalOtherStudentDetail> GetAll();

    IEnumerable<ExternalOtherStudentDetail> Find(Expression<Func<ExternalOtherStudentDetail, bool>> where, params Expression<Func<ExternalOtherStudentDetail, object>>[] includes);
		
    }

}
