//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IExternalStudentSchoolDetailsManager
	{

    void Add(ExternalStudentSchoolDetail ExternalStudentSchoolDetail);

    void Update(ExternalStudentSchoolDetail ExternalStudentSchoolDetail);

    void Delete(ExternalStudentSchoolDetail ExternalStudentSchoolDetail);

    ExternalStudentSchoolDetail GetById(short id);
      
    IList<ExternalStudentSchoolDetail> GetAll();

    IEnumerable<ExternalStudentSchoolDetail> Find(Expression<Func<ExternalStudentSchoolDetail, bool>> where, params Expression<Func<ExternalStudentSchoolDetail, object>>[] includes);
		
    }

}






