//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IExternalStudentAdresssManager
	{

    void Add(ExternalStudentAdress ExternalStudentAdress);

    void Update(ExternalStudentAdress ExternalStudentAdress);

    void Delete(ExternalStudentAdress ExternalStudentAdress);

    ExternalStudentAdress GetById(short id);
      
    IList<ExternalStudentAdress> GetAll();

    IEnumerable<ExternalStudentAdress> Find(Expression<Func<ExternalStudentAdress, bool>> where, params Expression<Func<ExternalStudentAdress, object>>[] includes);
		
    }

}






