//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IFeesManager
	{

    void Add(Fee Fee);

    void Update(Fee Fee);

    void Delete(Fee Fee);

    Fee GetById(short id);
      
    IList<Fee> GetAll();

    IEnumerable<Fee> Find(Expression<Func<Fee, bool>> where, params Expression<Func<Fee, object>>[] includes);
		
    }

}
