//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IFunctionsManager
	{

    void Add(Function Function);

    void Update(Function Function);

    void Delete(Function Function);

    Function GetById(short id);
      
    IList<Function> GetAll();

    IEnumerable<Function> Find(Expression<Func<Function, bool>> where, params Expression<Func<Function, object>>[] includes);
		
    }

}
