//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IGuardiansManager
	{

    void Add(Guardian Guardian);

    void Update(Guardian Guardian);

    void Delete(Guardian Guardian);

    Guardian GetById(short id);
      
    IList<Guardian> GetAll();

    IEnumerable<Guardian> Find(Expression<Func<Guardian, bool>> where, params Expression<Func<Guardian, object>>[] includes);
		
    }

}
