//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IImportanceTypesManager
	{

    void Add(ImportanceType ImportanceType);

    void Update(ImportanceType ImportanceType);

    void Delete(ImportanceType ImportanceType);

    ImportanceType GetById(short id);
      
    IList<ImportanceType> GetAll();

    IEnumerable<ImportanceType> Find(Expression<Func<ImportanceType, bool>> where, params Expression<Func<ImportanceType, object>>[] includes);
		
    }

}
