//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ILanguagesManager
	{

    void Add(Language Language);

    void Update(Language Language);

    void Delete(Language Language);

    Language GetById(short id);
      
    IList<Language> GetAll();

    IEnumerable<Language> Find(Expression<Func<Language, bool>> where, params Expression<Func<Language, object>>[] includes);
		
    }

}
