//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ILiveswithTypesManager
	{

    void Add(LiveswithType LiveswithType);

    void Update(LiveswithType LiveswithType);

    void Delete(LiveswithType LiveswithType);

    LiveswithType GetById(short id);
      
    IList<LiveswithType> GetAll();

    IEnumerable<LiveswithType> Find(Expression<Func<LiveswithType, bool>> where, params Expression<Func<LiveswithType, object>>[] includes);
		
    }

}
