//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ILogsManager
	{

    void Add(Log Log);

    void Update(Log Log);

    void Delete(Log Log);

    Log GetById(short id);
      
    IList<Log> GetAll();

    IEnumerable<Log> Find(Expression<Func<Log, bool>> where, params Expression<Func<Log, object>>[] includes);
		
    }

}
