//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ILookupValuesManager
	{

    void Add(LookupValue LookupValue);

    void Update(LookupValue LookupValue);

    void Delete(LookupValue LookupValue);

    LookupValue GetById(short id);
      
    IList<LookupValue> GetAll();

    IEnumerable<LookupValue> Find(Expression<Func<LookupValue, bool>> where, params Expression<Func<LookupValue, object>>[] includes);
		
    }

}
