//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IMailTemplatesManager
	{

    void Add(MailTemplate MailTemplate);

    void Update(MailTemplate MailTemplate);

    void Delete(MailTemplate MailTemplate);

    MailTemplate GetById(short id);
      
    IList<MailTemplate> GetAll();

    IEnumerable<MailTemplate> Find(Expression<Func<MailTemplate, bool>> where, params Expression<Func<MailTemplate, object>>[] includes);
		
    }

}






