//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IManualTimetablesManager
	{

    void Add(ManualTimetable ManualTimetable);

    void Update(ManualTimetable ManualTimetable);

    void Delete(ManualTimetable ManualTimetable);

    ManualTimetable GetById(short id);
      
    IList<ManualTimetable> GetAll();

    IEnumerable<ManualTimetable> Find(Expression<Func<ManualTimetable, bool>> where, params Expression<Func<ManualTimetable, object>>[] includes);
		
    }

}
