//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IMappedFieldsManager
	{

    void Add(MappedField MappedField);

    void Update(MappedField MappedField);

    void Delete(MappedField MappedField);

    MappedField GetById(short id);
      
    IList<MappedField> GetAll();

    IEnumerable<MappedField> Find(Expression<Func<MappedField, bool>> where, params Expression<Func<MappedField, object>>[] includes);
		
    }

}
