//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IMaritalStatussManager
	{

    void Add(MaritalStatus MaritalStatus);

    void Update(MaritalStatus MaritalStatus);

    void Delete(MaritalStatus MaritalStatus);

    MaritalStatus GetById(short id);
      
    IList<MaritalStatus> GetAll();

    IEnumerable<MaritalStatus> Find(Expression<Func<MaritalStatus, bool>> where, params Expression<Func<MaritalStatus, object>>[] includes);
		
    }

}
