//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IMSTeams_SessionAttendessManager
	{

    void Add(MSTeams_SessionAttendes MSTeams_SessionAttendes);

    void Update(MSTeams_SessionAttendes MSTeams_SessionAttendes);

    void Delete(MSTeams_SessionAttendes MSTeams_SessionAttendes);

    MSTeams_SessionAttendes GetById(short id);
      
    IList<MSTeams_SessionAttendes> GetAll();

    IEnumerable<MSTeams_SessionAttendes> Find(Expression<Func<MSTeams_SessionAttendes, bool>> where, params Expression<Func<MSTeams_SessionAttendes, object>>[] includes);
		
    }

}
