//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface INotificationsManager
	{

    void Add(Notification Notification);

    void Update(Notification Notification);

    void Delete(Notification Notification);

    Notification GetById(short id);
      
    IList<Notification> GetAll();

    IEnumerable<Notification> Find(Expression<Func<Notification, bool>> where, params Expression<Func<Notification, object>>[] includes);
		
    }

}
