//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IOtherStudentDetailsManager
	{

    void Add(OtherStudentDetail OtherStudentDetail);

    void Update(OtherStudentDetail OtherStudentDetail);

    void Delete(OtherStudentDetail OtherStudentDetail);

    OtherStudentDetail GetById(short id);
      
    IList<OtherStudentDetail> GetAll();

    IEnumerable<OtherStudentDetail> Find(Expression<Func<OtherStudentDetail, bool>> where, params Expression<Func<OtherStudentDetail, object>>[] includes);
		
    }

}






