//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IPaymentMethodsManager
	{

    void Add(PaymentMethod PaymentMethod);

    void Update(PaymentMethod PaymentMethod);

    void Delete(PaymentMethod PaymentMethod);

    PaymentMethod GetById(short id);
      
    IList<PaymentMethod> GetAll();

    IEnumerable<PaymentMethod> Find(Expression<Func<PaymentMethod, bool>> where, params Expression<Func<PaymentMethod, object>>[] includes);
		
    }

}
