//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IPrivilagesManager
	{

    void Add(Privilage Privilage);

    void Update(Privilage Privilage);

    void Delete(Privilage Privilage);

    Privilage GetById(short id);
      
    IList<Privilage> GetAll();

    IEnumerable<Privilage> Find(Expression<Func<Privilage, bool>> where, params Expression<Func<Privilage, object>>[] includes);
		
    }

}
