//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IQualificationsManager
	{

    void Add(Qualification Qualification);

    void Update(Qualification Qualification);

    void Delete(Qualification Qualification);

    Qualification GetById(short id);
      
    IList<Qualification> GetAll();

    IEnumerable<Qualification> Find(Expression<Func<Qualification, bool>> where, params Expression<Func<Qualification, object>>[] includes);
		
    }

}
