//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IQuestionTypesManager
	{

    void Add(QuestionType QuestionType);

    void Update(QuestionType QuestionType);

    void Delete(QuestionType QuestionType);

    QuestionType GetById(short id);
      
    IList<QuestionType> GetAll();

    IEnumerable<QuestionType> Find(Expression<Func<QuestionType, bool>> where, params Expression<Func<QuestionType, object>>[] includes);
		
    }

}
