//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IQuestionLevelsManager
	{

    void Add(QuestionLevel QuestionLevel);

    void Update(QuestionLevel QuestionLevel);

    void Delete(QuestionLevel QuestionLevel);

    QuestionLevel GetById(short id);
      
    IList<QuestionLevel> GetAll();

    IEnumerable<QuestionLevel> Find(Expression<Func<QuestionLevel, bool>> where, params Expression<Func<QuestionLevel, object>>[] includes);
		
    }

}
