//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IQuestionBanksManager
	{

    void Add(QuestionBank QuestionBank);

    void Update(QuestionBank QuestionBank);

    void Delete(QuestionBank QuestionBank);

    QuestionBank GetById(short id);
      
    IList<QuestionBank> GetAll();

    IEnumerable<QuestionBank> Find(Expression<Func<QuestionBank, bool>> where, params Expression<Func<QuestionBank, object>>[] includes);
		
    }

}
