//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IRecurrenceTypesManager
	{

    void Add(RecurrenceType RecurrenceType);

    void Update(RecurrenceType RecurrenceType);

    void Delete(RecurrenceType RecurrenceType);

    RecurrenceType GetById(short id);
      
    IList<RecurrenceType> GetAll();

    IEnumerable<RecurrenceType> Find(Expression<Func<RecurrenceType, bool>> where, params Expression<Func<RecurrenceType, object>>[] includes);
		
    }

}
