//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IReligionsManager
	{

    void Add(Religion Religion);

    void Update(Religion Religion);

    void Delete(Religion Religion);

    Religion GetById(short id);
      
    IList<Religion> GetAll();

    IEnumerable<Religion> Find(Expression<Func<Religion, bool>> where, params Expression<Func<Religion, object>>[] includes);
		
    }

}
