//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISchoolClasssManager
	{

    void Add(SchoolClass SchoolClass);

    void Update(SchoolClass SchoolClass);

    void Delete(SchoolClass SchoolClass);

    SchoolClass GetById(short id);
      
    IList<SchoolClass> GetAll();

    IEnumerable<SchoolClass> Find(Expression<Func<SchoolClass, bool>> where, params Expression<Func<SchoolClass, object>>[] includes);
		
    }

}
