//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISectionsManager
	{

    void Add(Section Section);

    void Update(Section Section);

    void Delete(Section Section);

    Section GetById(short id);
      
    IList<Section> GetAll();

    IEnumerable<Section> Find(Expression<Func<Section, bool>> where, params Expression<Func<Section, object>>[] includes);
		
    }

}
