//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISessionsManager
	{

    void Add(Session Session);

    void Update(Session Session);

    void Delete(Session Session);

    Session GetById(short id);
      
    IList<Session> GetAll();

    IEnumerable<Session> Find(Expression<Func<Session, bool>> where, params Expression<Func<Session, object>>[] includes);
		
    }

}
