//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISessionDistributionsManager
	{

    void Add(SessionDistribution SessionDistribution);

    void Update(SessionDistribution SessionDistribution);

    void Delete(SessionDistribution SessionDistribution);

    SessionDistribution GetById(short id);
      
    IList<SessionDistribution> GetAll();

    IEnumerable<SessionDistribution> Find(Expression<Func<SessionDistribution, bool>> where, params Expression<Func<SessionDistribution, object>>[] includes);
		
    }

}
