//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISpecializationsManager
	{

    void Add(Specialization Specialization);

    void Update(Specialization Specialization);

    void Delete(Specialization Specialization);

    Specialization GetById(short id);
      
    IList<Specialization> GetAll();

    IEnumerable<Specialization> Find(Expression<Func<Specialization, bool>> where, params Expression<Func<Specialization, object>>[] includes);
		
    }

}
