//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStaffBankDetailsManager
	{

    void Add(StaffBankDetail StaffBankDetail);

    void Update(StaffBankDetail StaffBankDetail);

    void Delete(StaffBankDetail StaffBankDetail);

    StaffBankDetail GetById(short id);
      
    IList<StaffBankDetail> GetAll();

    IEnumerable<StaffBankDetail> Find(Expression<Func<StaffBankDetail, bool>> where, params Expression<Func<StaffBankDetail, object>>[] includes);
		
    }

}
