//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStaffContactDetailsManager
	{

    void Add(StaffContactDetail StaffContactDetail);

    void Update(StaffContactDetail StaffContactDetail);

    void Delete(StaffContactDetail StaffContactDetail);

    StaffContactDetail GetById(short id);
      
    IList<StaffContactDetail> GetAll();

    IEnumerable<StaffContactDetail> Find(Expression<Func<StaffContactDetail, bool>> where, params Expression<Func<StaffContactDetail, object>>[] includes);
		
    }

}
