//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStaffSalaryDetailsManager
	{

    void Add(StaffSalaryDetail StaffSalaryDetail);

    void Update(StaffSalaryDetail StaffSalaryDetail);

    void Delete(StaffSalaryDetail StaffSalaryDetail);

    StaffSalaryDetail GetById(short id);
      
    IList<StaffSalaryDetail> GetAll();

    IEnumerable<StaffSalaryDetail> Find(Expression<Func<StaffSalaryDetail, bool>> where, params Expression<Func<StaffSalaryDetail, object>>[] includes);
		
    }

}
