//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStaffLeafsManager
	{

    void Add(StaffLeaf StaffLeaf);

    void Update(StaffLeaf StaffLeaf);

    void Delete(StaffLeaf StaffLeaf);

    StaffLeaf GetById(short id);
      
    IList<StaffLeaf> GetAll();

    IEnumerable<StaffLeaf> Find(Expression<Func<StaffLeaf, bool>> where, params Expression<Func<StaffLeaf, object>>[] includes);
		
    }

}
