//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStaffJobDetailsManager
	{

    void Add(StaffJobDetail StaffJobDetail);

    void Update(StaffJobDetail StaffJobDetail);

    void Delete(StaffJobDetail StaffJobDetail);

    StaffJobDetail GetById(short id);
      
    IList<StaffJobDetail> GetAll();

    IEnumerable<StaffJobDetail> Find(Expression<Func<StaffJobDetail, bool>> where, params Expression<Func<StaffJobDetail, object>>[] includes);
		
    }

}
