//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentSchoolDetailsManager
	{

    void Add(StudentSchoolDetail StudentSchoolDetail);

    void Update(StudentSchoolDetail StudentSchoolDetail);

    void Delete(StudentSchoolDetail StudentSchoolDetail);

    StudentSchoolDetail GetById(short id);
      
    IList<StudentSchoolDetail> GetAll();

    IEnumerable<StudentSchoolDetail> Find(Expression<Func<StudentSchoolDetail, bool>> where, params Expression<Func<StudentSchoolDetail, object>>[] includes);
		
    }

}
