//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentBehaviorsManager
	{

    void Add(StudentBehavior StudentBehavior);

    void Update(StudentBehavior StudentBehavior);

    void Delete(StudentBehavior StudentBehavior);

    StudentBehavior GetById(short id);
      
    IList<StudentBehavior> GetAll();

    IEnumerable<StudentBehavior> Find(Expression<Func<StudentBehavior, bool>> where, params Expression<Func<StudentBehavior, object>>[] includes);
		
    }

}
