//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentFeesManager
	{

    void Add(StudentFee StudentFee);

    void Update(StudentFee StudentFee);

    void Delete(StudentFee StudentFee);

    StudentFee GetById(short id);
      
    IList<StudentFee> GetAll();

    IEnumerable<StudentFee> Find(Expression<Func<StudentFee, bool>> where, params Expression<Func<StudentFee, object>>[] includes);
		
    }

}
