//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentGuardDetailsManager
	{

    void Add(StudentGuardDetail StudentGuardDetail);

    void Update(StudentGuardDetail StudentGuardDetail);

    void Delete(StudentGuardDetail StudentGuardDetail);

    StudentGuardDetail GetById(short id);
      
    IList<StudentGuardDetail> GetAll();

    IEnumerable<StudentGuardDetail> Find(Expression<Func<StudentGuardDetail, bool>> where, params Expression<Func<StudentGuardDetail, object>>[] includes);
		
    }

}






