//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentAdresssManager
	{

    void Add(StudentAdress StudentAdress);

    void Update(StudentAdress StudentAdress);

    void Delete(StudentAdress StudentAdress);

    StudentAdress GetById(short id);
      
    IList<StudentAdress> GetAll();

    IEnumerable<StudentAdress> Find(Expression<Func<StudentAdress, bool>> where, params Expression<Func<StudentAdress, object>>[] includes);
		
    }

}
