//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentResultsManager
	{

    void Add(StudentResult StudentResult);

    void Update(StudentResult StudentResult);

    void Delete(StudentResult StudentResult);

    StudentResult GetById(short id);
      
    IList<StudentResult> GetAll();

    IEnumerable<StudentResult> Find(Expression<Func<StudentResult, bool>> where, params Expression<Func<StudentResult, object>>[] includes);
		
    }

}
