//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IStudentDiseassManager
	{

    void Add(StudentDiseas StudentDiseas);

    void Update(StudentDiseas StudentDiseas);

    void Delete(StudentDiseas StudentDiseas);

    StudentDiseas GetById(short id);
      
    IList<StudentDiseas> GetAll();

    IEnumerable<StudentDiseas> Find(Expression<Func<StudentDiseas, bool>> where, params Expression<Func<StudentDiseas, object>>[] includes);
		
    }

}






