//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISystemSettingsManager
	{

    void Add(SystemSetting SystemSetting);

    void Update(SystemSetting SystemSetting);

    void Delete(SystemSetting SystemSetting);

    SystemSetting GetById(short id);
      
    IList<SystemSetting> GetAll();

    IEnumerable<SystemSetting> Find(Expression<Func<SystemSetting, bool>> where, params Expression<Func<SystemSetting, object>>[] includes);
		
    }

}
