//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISystemSettingsperSchoolsManager
	{

    void Add(SystemSettingsperSchool SystemSettingsperSchool);

    void Update(SystemSettingsperSchool SystemSettingsperSchool);

    void Delete(SystemSettingsperSchool SystemSettingsperSchool);

    SystemSettingsperSchool GetById(short id);
      
    IList<SystemSettingsperSchool> GetAll();

    IEnumerable<SystemSettingsperSchool> Find(Expression<Func<SystemSettingsperSchool, bool>> where, params Expression<Func<SystemSettingsperSchool, object>>[] includes);
		
    }

}
