//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ISystemObjectsManager
	{

    void Add(SystemObject SystemObject);

    void Update(SystemObject SystemObject);

    void Delete(SystemObject SystemObject);

    SystemObject GetById(short id);
      
    IList<SystemObject> GetAll();

    IEnumerable<SystemObject> Find(Expression<Func<SystemObject, bool>> where, params Expression<Func<SystemObject, object>>[] includes);
		
    }

}
