//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITeachersManager
	{

    void Add(Teacher Teacher);

    void Update(Teacher Teacher);

    void Delete(Teacher Teacher);

    Teacher GetById(short id);
      
    IList<Teacher> GetAll();

    IEnumerable<Teacher> Find(Expression<Func<Teacher, bool>> where, params Expression<Func<Teacher, object>>[] includes);
		
    }

}
