//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITeacherExperiencesManager
	{

    void Add(TeacherExperience TeacherExperience);

    void Update(TeacherExperience TeacherExperience);

    void Delete(TeacherExperience TeacherExperience);

    TeacherExperience GetById(short id);
      
    IList<TeacherExperience> GetAll();

    IEnumerable<TeacherExperience> Find(Expression<Func<TeacherExperience, bool>> where, params Expression<Func<TeacherExperience, object>>[] includes);
		
    }

}
