//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITemplateSettingsManager
	{

    void Add(TemplateSetting TemplateSetting);

    void Update(TemplateSetting TemplateSetting);

    void Delete(TemplateSetting TemplateSetting);

    TemplateSetting GetById(short id);
      
    IList<TemplateSetting> GetAll();

    IEnumerable<TemplateSetting> Find(Expression<Func<TemplateSetting, bool>> where, params Expression<Func<TemplateSetting, object>>[] includes);
		
    }

}
