//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITimetableItemsManager
	{

    void Add(TimetableItem TimetableItem);

    void Update(TimetableItem TimetableItem);

    void Delete(TimetableItem TimetableItem);

    TimetableItem GetById(short id);
      
    IList<TimetableItem> GetAll();

    IEnumerable<TimetableItem> Find(Expression<Func<TimetableItem, bool>> where, params Expression<Func<TimetableItem, object>>[] includes);
		
    }

}
