//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITimetableConditionsManager
	{

    void Add(TimetableCondition TimetableCondition);

    void Update(TimetableCondition TimetableCondition);

    void Delete(TimetableCondition TimetableCondition);

    TimetableCondition GetById(short id);
      
    IList<TimetableCondition> GetAll();

    IEnumerable<TimetableCondition> Find(Expression<Func<TimetableCondition, bool>> where, params Expression<Func<TimetableCondition, object>>[] includes);
		
    }

}
