//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITimetablesManager
	{

    void Add(Timetable Timetable);

    void Update(Timetable Timetable);

    void Delete(Timetable Timetable);

    Timetable GetById(short id);
      
    IList<Timetable> GetAll();

    IEnumerable<Timetable> Find(Expression<Func<Timetable, bool>> where, params Expression<Func<Timetable, object>>[] includes);
		
    }

}
