//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITransportCategoryTypesManager
	{

    void Add(TransportCategoryType TransportCategoryType);

    void Update(TransportCategoryType TransportCategoryType);

    void Delete(TransportCategoryType TransportCategoryType);

    TransportCategoryType GetById(short id);
      
    IList<TransportCategoryType> GetAll();

    IEnumerable<TransportCategoryType> Find(Expression<Func<TransportCategoryType, bool>> where, params Expression<Func<TransportCategoryType, object>>[] includes);
		
    }

}
