//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface ITransportCategorysManager
	{

    void Add(TransportCategory TransportCategory);

    void Update(TransportCategory TransportCategory);

    void Delete(TransportCategory TransportCategory);

    TransportCategory GetById(short id);
      
    IList<TransportCategory> GetAll();

    IEnumerable<TransportCategory> Find(Expression<Func<TransportCategory, bool>> where, params Expression<Func<TransportCategory, object>>[] includes);
		
    }

}
