//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IUserTypesManager
	{

    void Add(UserType UserType);

    void Update(UserType UserType);

    void Delete(UserType UserType);

    UserType GetById(short id);
      
    IList<UserType> GetAll();

    IEnumerable<UserType> Find(Expression<Func<UserType, bool>> where, params Expression<Func<UserType, object>>[] includes);
		
    }

}
