//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
using Objects.DTO;

namespace Business.Interfaces
{
public interface IUsersManager
	{

    void Add(User User);

    void Update(User User);

    void Delete(User User);

    User GetById(short id);
      
    IList<User> GetAll();

    IEnumerable<User> Find(Expression<Func<User, bool>> where, params Expression<Func<User, object>>[] includes);
    UserDTO GetUserLogin(string username, string password,bool asparent, bool asStudent, string lang);
    }

}
