//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using System.Linq.Expressions;
using Objects;
namespace Business.Interfaces
{
public interface IWifesManager
	{

    void Add(Wife Wife);

    void Update(Wife Wife);

    void Delete(Wife Wife);

    Wife GetById(short id);
      
    IList<Wife> GetAll();

    IEnumerable<Wife> Find(Expression<Func<Wife, bool>> where, params Expression<Func<Wife, object>>[] includes);
		
    }

}






