//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class BusAttendanceSchedulesManager : BusinessComponentBase, IBusAttendanceSchedulesManager
{


    public BusAttendanceSchedulesManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(BusAttendanceSchedule BusAttendanceSchedule)
    {

DataAccessFactory.GetBusAttendanceSchedulesRepository.Add(BusAttendanceSchedule);
            DataAccessFactory.Commit();

}

public void Update(BusAttendanceSchedule BusAttendanceSchedule)
    {

DataAccessFactory.GetBusAttendanceSchedulesRepository.Update(BusAttendanceSchedule);
        DataAccessFactory.Commit();

}

public void Delete(BusAttendanceSchedule BusAttendanceSchedule)
    {

DataAccessFactory.GetBusAttendanceSchedulesRepository.Delete(BusAttendanceSchedule);
            DataAccessFactory.Commit();

}

public BusAttendanceSchedule GetById(short id)
    {
        BusAttendanceSchedule BusAttendanceSchedule = null;

        //  BusAttendanceSchedule =  DataAccessFactory.GetBusAttendanceSchedulesRepository.First(_BusAttendanceSchedule => _BusAttendanceSchedule.BusAttendanceScheduleID == id);

        return BusAttendanceSchedule;
    }

    public IList<BusAttendanceSchedule> GetAll()
    {
        IEnumerable<BusAttendanceSchedule> BusAttendanceSchedules = null;

        BusAttendanceSchedules = DataAccessFactory.GetBusAttendanceSchedulesRepository.GetAll();

        IList<BusAttendanceSchedule> result = BusAttendanceSchedules.ToList<BusAttendanceSchedule>();

        return result;
    }
		
    public IEnumerable<BusAttendanceSchedule> Find(Expression<Func<BusAttendanceSchedule, bool>> @where, params Expression<Func<BusAttendanceSchedule, object>>[] includes)
    {
        return  DataAccessFactory.GetBusAttendanceSchedulesRepository.Find(@where, includes);
    }
		



        		

}

}
