//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class ClasssManager : BusinessComponentBase, IClasssManager
{


    public ClasssManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(Class Class)
    {

DataAccessFactory.GetClasssRepository.Add(Class);
            DataAccessFactory.Commit();

}

public void Update(Class Class)
    {

DataAccessFactory.GetClasssRepository.Update(Class);
        DataAccessFactory.Commit();

}

public void Delete(Class Class)
    {

DataAccessFactory.GetClasssRepository.Delete(Class);
            DataAccessFactory.Commit();

}

public Class GetById(short id)
    {
        Class Class = null;

        //  Class =  DataAccessFactory.GetClasssRepository.First(_Class => _Class.ClassID == id);

        return Class;
    }

    public IList<Class> GetAll()
    {
        IEnumerable<Class> Classs = null;

        Classs = DataAccessFactory.GetClasssRepository.GetAll();

        IList<Class> result = Classs.ToList<Class>();

        return result;
    }
		
    public IEnumerable<Class> Find(Expression<Func<Class, bool>> @where, params Expression<Func<Class, object>>[] includes)
    {
        return  DataAccessFactory.GetClasssRepository.Find(@where, includes);
    }
		



        		

}

}
