//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class CurriculumsManager : BusinessComponentBase, ICurriculumsManager
{


    public CurriculumsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(Curriculum Curriculum)
    {

DataAccessFactory.GetCurriculumsRepository.Add(Curriculum);
            DataAccessFactory.Commit();

}

public void Update(Curriculum Curriculum)
    {

DataAccessFactory.GetCurriculumsRepository.Update(Curriculum);
        DataAccessFactory.Commit();

}

public void Delete(Curriculum Curriculum)
    {

DataAccessFactory.GetCurriculumsRepository.Delete(Curriculum);
            DataAccessFactory.Commit();

}

public Curriculum GetById(short id)
    {
        Curriculum Curriculum = null;

        //  Curriculum =  DataAccessFactory.GetCurriculumsRepository.First(_Curriculum => _Curriculum.CurriculumID == id);

        return Curriculum;
    }

    public IList<Curriculum> GetAll()
    {
        IEnumerable<Curriculum> Curriculums = null;

        Curriculums = DataAccessFactory.GetCurriculumsRepository.GetAll();

        IList<Curriculum> result = Curriculums.ToList<Curriculum>();

        return result;
    }
		
    public IEnumerable<Curriculum> Find(Expression<Func<Curriculum, bool>> @where, params Expression<Func<Curriculum, object>>[] includes)
    {
        return  DataAccessFactory.GetCurriculumsRepository.Find(@where, includes);
    }
		



        		

}

}
