//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class DiscountStudentsManager : BusinessComponentBase, IDiscountStudentsManager
{


    public DiscountStudentsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(DiscountStudent DiscountStudent)
    {

DataAccessFactory.GetDiscountStudentsRepository.Add(DiscountStudent);
            DataAccessFactory.Commit();

}

public void Update(DiscountStudent DiscountStudent)
    {

DataAccessFactory.GetDiscountStudentsRepository.Update(DiscountStudent);
        DataAccessFactory.Commit();

}

public void Delete(DiscountStudent DiscountStudent)
    {

DataAccessFactory.GetDiscountStudentsRepository.Delete(DiscountStudent);
            DataAccessFactory.Commit();

}

public DiscountStudent GetById(short id)
    {
        DiscountStudent DiscountStudent = null;

        //  DiscountStudent =  DataAccessFactory.GetDiscountStudentsRepository.First(_DiscountStudent => _DiscountStudent.DiscountStudentID == id);

        return DiscountStudent;
    }

    public IList<DiscountStudent> GetAll()
    {
        IEnumerable<DiscountStudent> DiscountStudents = null;

        DiscountStudents = DataAccessFactory.GetDiscountStudentsRepository.GetAll();

        IList<DiscountStudent> result = DiscountStudents.ToList<DiscountStudent>();

        return result;
    }
		
    public IEnumerable<DiscountStudent> Find(Expression<Func<DiscountStudent, bool>> @where, params Expression<Func<DiscountStudent, object>>[] includes)
    {
        return  DataAccessFactory.GetDiscountStudentsRepository.Find(@where, includes);
    }
		



        		

}

}
