//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class ExternalStudentSchoolDetailsManager : BusinessComponentBase, IExternalStudentSchoolDetailsManager
{


    public ExternalStudentSchoolDetailsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(ExternalStudentSchoolDetail ExternalStudentSchoolDetail)
    {

DataAccessFactory.GetExternalStudentSchoolDetailsRepository.Add(ExternalStudentSchoolDetail);
            DataAccessFactory.Commit();

}

public void Update(ExternalStudentSchoolDetail ExternalStudentSchoolDetail)
    {

DataAccessFactory.GetExternalStudentSchoolDetailsRepository.Update(ExternalStudentSchoolDetail);
        DataAccessFactory.Commit();

}

public void Delete(ExternalStudentSchoolDetail ExternalStudentSchoolDetail)
    {

DataAccessFactory.GetExternalStudentSchoolDetailsRepository.Delete(ExternalStudentSchoolDetail);
            DataAccessFactory.Commit();

}

public ExternalStudentSchoolDetail GetById(short id)
    {
        ExternalStudentSchoolDetail ExternalStudentSchoolDetail = null;

        //  ExternalStudentSchoolDetail =  DataAccessFactory.GetExternalStudentSchoolDetailsRepository.First(_ExternalStudentSchoolDetail => _ExternalStudentSchoolDetail.ExternalStudentSchoolDetailID == id);

        return ExternalStudentSchoolDetail;
    }

    public IList<ExternalStudentSchoolDetail> GetAll()
    {
        IEnumerable<ExternalStudentSchoolDetail> ExternalStudentSchoolDetails = null;

        ExternalStudentSchoolDetails = DataAccessFactory.GetExternalStudentSchoolDetailsRepository.GetAll();

        IList<ExternalStudentSchoolDetail> result = ExternalStudentSchoolDetails.ToList<ExternalStudentSchoolDetail>();

        return result;
    }
		
    public IEnumerable<ExternalStudentSchoolDetail> Find(Expression<Func<ExternalStudentSchoolDetail, bool>> @where, params Expression<Func<ExternalStudentSchoolDetail, object>>[] includes)
    {
        return  DataAccessFactory.GetExternalStudentSchoolDetailsRepository.Find(@where, includes);
    }
		



        		

}

}

