//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class ExternalGuardStudentsRequestsManager : BusinessComponentBase, IExternalGuardStudentsRequestsManager
{


    public ExternalGuardStudentsRequestsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(ExternalGuardStudentsRequest ExternalGuardStudentsRequest)
    {

DataAccessFactory.GetExternalGuardStudentsRequestsRepository.Add(ExternalGuardStudentsRequest);
            DataAccessFactory.Commit();

}

public void Update(ExternalGuardStudentsRequest ExternalGuardStudentsRequest)
    {

DataAccessFactory.GetExternalGuardStudentsRequestsRepository.Update(ExternalGuardStudentsRequest);
        DataAccessFactory.Commit();

}

public void Delete(ExternalGuardStudentsRequest ExternalGuardStudentsRequest)
    {

DataAccessFactory.GetExternalGuardStudentsRequestsRepository.Delete(ExternalGuardStudentsRequest);
            DataAccessFactory.Commit();

}

public ExternalGuardStudentsRequest GetById(short id)
    {
        ExternalGuardStudentsRequest ExternalGuardStudentsRequest = null;

        //  ExternalGuardStudentsRequest =  DataAccessFactory.GetExternalGuardStudentsRequestsRepository.First(_ExternalGuardStudentsRequest => _ExternalGuardStudentsRequest.ExternalGuardStudentsRequestID == id);

        return ExternalGuardStudentsRequest;
    }

    public IList<ExternalGuardStudentsRequest> GetAll()
    {
        IEnumerable<ExternalGuardStudentsRequest> ExternalGuardStudentsRequests = null;

        ExternalGuardStudentsRequests = DataAccessFactory.GetExternalGuardStudentsRequestsRepository.GetAll();

        IList<ExternalGuardStudentsRequest> result = ExternalGuardStudentsRequests.ToList<ExternalGuardStudentsRequest>();

        return result;
    }
		
    public IEnumerable<ExternalGuardStudentsRequest> Find(Expression<Func<ExternalGuardStudentsRequest, bool>> @where, params Expression<Func<ExternalGuardStudentsRequest, object>>[] includes)
    {
        return  DataAccessFactory.GetExternalGuardStudentsRequestsRepository.Find(@where, includes);
    }
		



        		

}

}

