//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class ExternalGuardiansManager : BusinessComponentBase, IExternalGuardiansManager
{


    public ExternalGuardiansManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(ExternalGuardian ExternalGuardian)
    {

DataAccessFactory.GetExternalGuardiansRepository.Add(ExternalGuardian);
            DataAccessFactory.Commit();

}

public void Update(ExternalGuardian ExternalGuardian)
    {

DataAccessFactory.GetExternalGuardiansRepository.Update(ExternalGuardian);
        DataAccessFactory.Commit();

}

public void Delete(ExternalGuardian ExternalGuardian)
    {

DataAccessFactory.GetExternalGuardiansRepository.Delete(ExternalGuardian);
            DataAccessFactory.Commit();

}

public ExternalGuardian GetById(short id)
    {
        ExternalGuardian ExternalGuardian = null;

        //  ExternalGuardian =  DataAccessFactory.GetExternalGuardiansRepository.First(_ExternalGuardian => _ExternalGuardian.ExternalGuardianID == id);

        return ExternalGuardian;
    }

    public IList<ExternalGuardian> GetAll()
    {
        IEnumerable<ExternalGuardian> ExternalGuardians = null;

        ExternalGuardians = DataAccessFactory.GetExternalGuardiansRepository.GetAll();

        IList<ExternalGuardian> result = ExternalGuardians.ToList<ExternalGuardian>();

        return result;
    }
		
    public IEnumerable<ExternalGuardian> Find(Expression<Func<ExternalGuardian, bool>> @where, params Expression<Func<ExternalGuardian, object>>[] includes)
    {
        return  DataAccessFactory.GetExternalGuardiansRepository.Find(@where, includes);
    }
		



        		

}

}

