//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class ManualTimetablesManager : BusinessComponentBase, IManualTimetablesManager
{


    public ManualTimetablesManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(ManualTimetable ManualTimetable)
    {

DataAccessFactory.GetManualTimetablesRepository.Add(ManualTimetable);
            DataAccessFactory.Commit();

}

public void Update(ManualTimetable ManualTimetable)
    {

DataAccessFactory.GetManualTimetablesRepository.Update(ManualTimetable);
        DataAccessFactory.Commit();

}

public void Delete(ManualTimetable ManualTimetable)
    {

DataAccessFactory.GetManualTimetablesRepository.Delete(ManualTimetable);
            DataAccessFactory.Commit();

}

public ManualTimetable GetById(short id)
    {
        ManualTimetable ManualTimetable = null;

        //  ManualTimetable =  DataAccessFactory.GetManualTimetablesRepository.First(_ManualTimetable => _ManualTimetable.ManualTimetableID == id);

        return ManualTimetable;
    }

    public IList<ManualTimetable> GetAll()
    {
        IEnumerable<ManualTimetable> ManualTimetables = null;

        ManualTimetables = DataAccessFactory.GetManualTimetablesRepository.GetAll();

        IList<ManualTimetable> result = ManualTimetables.ToList<ManualTimetable>();

        return result;
    }
		
    public IEnumerable<ManualTimetable> Find(Expression<Func<ManualTimetable, bool>> @where, params Expression<Func<ManualTimetable, object>>[] includes)
    {
        return  DataAccessFactory.GetManualTimetablesRepository.Find(@where, includes);
    }
		



        		

}

}
