//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class SchoolSettingsManager : BusinessComponentBase, ISchoolSettingsManager
{


    public SchoolSettingsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(SchoolSetting SchoolSetting)
    {

DataAccessFactory.GetSchoolSettingsRepository.Add(SchoolSetting);
            DataAccessFactory.Commit();

}

public void Update(SchoolSetting SchoolSetting)
    {

DataAccessFactory.GetSchoolSettingsRepository.Update(SchoolSetting);
        DataAccessFactory.Commit();

}

public void Delete(SchoolSetting SchoolSetting)
    {

DataAccessFactory.GetSchoolSettingsRepository.Delete(SchoolSetting);
            DataAccessFactory.Commit();

}

public SchoolSetting GetById(short id)
    {
        SchoolSetting SchoolSetting = null;

        //  SchoolSetting =  DataAccessFactory.GetSchoolSettingsRepository.First(_SchoolSetting => _SchoolSetting.SchoolSettingID == id);

        return SchoolSetting;
    }

    public IList<SchoolSetting> GetAll()
    {
        IEnumerable<SchoolSetting> SchoolSettings = null;

        SchoolSettings = DataAccessFactory.GetSchoolSettingsRepository.GetAll();

        IList<SchoolSetting> result = SchoolSettings.ToList<SchoolSetting>();

        return result;
    }
		
    public IEnumerable<SchoolSetting> Find(Expression<Func<SchoolSetting, bool>> @where, params Expression<Func<SchoolSetting, object>>[] includes)
    {
        return  DataAccessFactory.GetSchoolSettingsRepository.Find(@where, includes);
    }
		



        		

}

}
