//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class StaffBankDetailsManager : BusinessComponentBase, IStaffBankDetailsManager
{


    public StaffBankDetailsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(StaffBankDetail StaffBankDetail)
    {

DataAccessFactory.GetStaffBankDetailsRepository.Add(StaffBankDetail);
            DataAccessFactory.Commit();

}

public void Update(StaffBankDetail StaffBankDetail)
    {

DataAccessFactory.GetStaffBankDetailsRepository.Update(StaffBankDetail);
        DataAccessFactory.Commit();

}

public void Delete(StaffBankDetail StaffBankDetail)
    {

DataAccessFactory.GetStaffBankDetailsRepository.Delete(StaffBankDetail);
            DataAccessFactory.Commit();

}

public StaffBankDetail GetById(short id)
    {
        StaffBankDetail StaffBankDetail = null;

        //  StaffBankDetail =  DataAccessFactory.GetStaffBankDetailsRepository.First(_StaffBankDetail => _StaffBankDetail.StaffBankDetailID == id);

        return StaffBankDetail;
    }

    public IList<StaffBankDetail> GetAll()
    {
        IEnumerable<StaffBankDetail> StaffBankDetails = null;

        StaffBankDetails = DataAccessFactory.GetStaffBankDetailsRepository.GetAll();

        IList<StaffBankDetail> result = StaffBankDetails.ToList<StaffBankDetail>();

        return result;
    }
		
    public IEnumerable<StaffBankDetail> Find(Expression<Func<StaffBankDetail, bool>> @where, params Expression<Func<StaffBankDetail, object>>[] includes)
    {
        return  DataAccessFactory.GetStaffBankDetailsRepository.Find(@where, includes);
    }
		



        		

}

}
