//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;
using Objects.DTO;

namespace Business.Managers
{
public class StudentsManager : BusinessComponentBase, IStudentsManager
{


    public StudentsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(Student Student)
    {

DataAccessFactory.GetStudentsRepository.Add(Student);
            DataAccessFactory.Commit();

}

public void Update(Student Student)
    {

DataAccessFactory.GetStudentsRepository.Update(Student);
        DataAccessFactory.Commit();

}

public void Delete(Student Student)
    {

DataAccessFactory.GetStudentsRepository.Delete(Student);
            DataAccessFactory.Commit();

}

public Student GetById(short id)
    {
        Student Student = null;

        //  Student =  DataAccessFactory.GetStudentsRepository.First(_Student => _Student.StudentID == id);

        return Student;
    }

    public IList<Student> GetAll()
    {
        IEnumerable<Student> Students = null;

        Students = DataAccessFactory.GetStudentsRepository.GetAll();

        IList<Student> result = Students.ToList<Student>();

        return result;
    }
		
    public IEnumerable<Student> Find(Expression<Func<Student, bool>> @where, params Expression<Func<Student, object>>[] includes)
    {
        return  DataAccessFactory.GetStudentsRepository.Find(@where, includes);
    }


        public List<StudentClassficationDTO> GetStudentStatistics(int SchoolID)
        {
            return DataAccessFactory.GetStudentsRepository.GetStudentStatistics(SchoolID);

        }




    }

}
