//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class StudentResultsManager : BusinessComponentBase, IStudentResultsManager
{


    public StudentResultsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(StudentResult StudentResult)
    {

DataAccessFactory.GetStudentResultsRepository.Add(StudentResult);
            DataAccessFactory.Commit();

}

public void Update(StudentResult StudentResult)
    {

DataAccessFactory.GetStudentResultsRepository.Update(StudentResult);
        DataAccessFactory.Commit();

}

public void Delete(StudentResult StudentResult)
    {

DataAccessFactory.GetStudentResultsRepository.Delete(StudentResult);
            DataAccessFactory.Commit();

}

public StudentResult GetById(short id)
    {
        StudentResult StudentResult = null;

        //  StudentResult =  DataAccessFactory.GetStudentResultsRepository.First(_StudentResult => _StudentResult.StudentResultID == id);

        return StudentResult;
    }

    public IList<StudentResult> GetAll()
    {
        IEnumerable<StudentResult> StudentResults = null;

        StudentResults = DataAccessFactory.GetStudentResultsRepository.GetAll();

        IList<StudentResult> result = StudentResults.ToList<StudentResult>();

        return result;
    }
		
    public IEnumerable<StudentResult> Find(Expression<Func<StudentResult, bool>> @where, params Expression<Func<StudentResult, object>>[] includes)
    {
        return  DataAccessFactory.GetStudentResultsRepository.Find(@where, includes);
    }
		



        		

}

}
