//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class StudentAdresssManager : BusinessComponentBase, IStudentAdresssManager
{


    public StudentAdresssManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(StudentAdress StudentAdress)
    {

DataAccessFactory.GetStudentAdresssRepository.Add(StudentAdress);
            DataAccessFactory.Commit();

}

public void Update(StudentAdress StudentAdress)
    {

DataAccessFactory.GetStudentAdresssRepository.Update(StudentAdress);
        DataAccessFactory.Commit();

}

public void Delete(StudentAdress StudentAdress)
    {

DataAccessFactory.GetStudentAdresssRepository.Delete(StudentAdress);
            DataAccessFactory.Commit();

}

public StudentAdress GetById(short id)
    {
        StudentAdress StudentAdress = null;

        //  StudentAdress =  DataAccessFactory.GetStudentAdresssRepository.First(_StudentAdress => _StudentAdress.StudentAdressID == id);

        return StudentAdress;
    }

    public IList<StudentAdress> GetAll()
    {
        IEnumerable<StudentAdress> StudentAdresss = null;

        StudentAdresss = DataAccessFactory.GetStudentAdresssRepository.GetAll();

        IList<StudentAdress> result = StudentAdresss.ToList<StudentAdress>();

        return result;
    }
		
    public IEnumerable<StudentAdress> Find(Expression<Func<StudentAdress, bool>> @where, params Expression<Func<StudentAdress, object>>[] includes)
    {
        return  DataAccessFactory.GetStudentAdresssRepository.Find(@where, includes);
    }
		



        		

}

}
