//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class Student_LoginsManager : BusinessComponentBase, IStudent_LoginsManager
{


    public Student_LoginsManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(Student_Login Student_Login)
    {

DataAccessFactory.GetStudent_LoginsRepository.Add(Student_Login);
            DataAccessFactory.Commit();

}

public void Update(Student_Login Student_Login)
    {

DataAccessFactory.GetStudent_LoginsRepository.Update(Student_Login);
        DataAccessFactory.Commit();

}

public void Delete(Student_Login Student_Login)
    {

DataAccessFactory.GetStudent_LoginsRepository.Delete(Student_Login);
            DataAccessFactory.Commit();

}

public Student_Login GetById(short id)
    {
        Student_Login Student_Login = null;

        //  Student_Login =  DataAccessFactory.GetStudent_LoginsRepository.First(_Student_Login => _Student_Login.Student_LoginID == id);

        return Student_Login;
    }

    public IList<Student_Login> GetAll()
    {
        IEnumerable<Student_Login> Student_Logins = null;

        Student_Logins = DataAccessFactory.GetStudent_LoginsRepository.GetAll();

        IList<Student_Login> result = Student_Logins.ToList<Student_Login>();

        return result;
    }
		
    public IEnumerable<Student_Login> Find(Expression<Func<Student_Login, bool>> @where, params Expression<Func<Student_Login, object>>[] includes)
    {
        return  DataAccessFactory.GetStudent_LoginsRepository.Find(@where, includes);
    }
		



        		

}

}

