//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Data.SqlClient;


using DataAccess;
using DataAccess.Base;
using Business.Base;
using Business.Interfaces;
using Objects;


 
namespace Business.Managers
{
public class StudentStatusManager : BusinessComponentBase, IStudentStatusManager
{


    public StudentStatusManager(IDataAccessFactory dataAccessFactory)
        : base(dataAccessFactory)
    {

    }

public void Add(StudentStatu StudentStatu)
    {

DataAccessFactory.GetStudentStatusRepository.Add(StudentStatu);
            DataAccessFactory.Commit();

}

public void Update(StudentStatu StudentStatu)
    {

DataAccessFactory.GetStudentStatusRepository.Update(StudentStatu);
        DataAccessFactory.Commit();

}

public void Delete(StudentStatu StudentStatu)
    {

DataAccessFactory.GetStudentStatusRepository.Delete(StudentStatu);
            DataAccessFactory.Commit();

}

public StudentStatu GetById(short id)
    {
        StudentStatu StudentStatu = null;

        //  StudentStatu =  DataAccessFactory.GetStudentStatusRepository.First(_StudentStatu => _StudentStatu.StudentStatuID == id);

        return StudentStatu;
    }

    public IList<StudentStatu> GetAll()
    {
        IEnumerable<StudentStatu> StudentStatus = null;

        StudentStatus = DataAccessFactory.GetStudentStatusRepository.GetAll();

        IList<StudentStatu> result = StudentStatus.ToList<StudentStatu>();

        return result;
    }
		
    public IEnumerable<StudentStatu> Find(Expression<Func<StudentStatu, bool>> @where, params Expression<Func<StudentStatu, object>>[] includes)
    {
        return  DataAccessFactory.GetStudentStatusRepository.Find(@where, includes);
    }
		



        		

}

}
